version: '3.8'

services:
  web:
    build:
      context: .
    container_name: bookmark_site_web
    command: python manage.py runserver 0.0.0.0:8030
    volumes:
      - .:/app
    ports:
      - "8030:8030"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=bookmark_site
      - DB_USER=root
      - DB_PASSWORD=rootpassword

  db:
    image: mysql:8.0
    container_name: mysql_db_web
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookmark_site
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

#volumes:
#  db_data:
